ALTER TABLE bank_credentials MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'INVALID', 'EXPIRED', 'INVISIBLE') DEFAULT 'ACTIVE';
ALTER TABLE tenant_banks_status MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'INVALID', 'EXPIRED', 'INVISIBLE') DEFAULT 'ACTIVE';
